### ISSUE TITLE
exclude the wasm binary from ggwave.js

### ISSUE THREAD

**Issue by thisconnect** [ggerganov/ggwave#19]
Ideally the wasm binary file would be a .wasm file

![Screen Shot 2021-02-14 at 1 54 37 PM](https://user-images.githubusercontent.com/546900/107877380-64e44f80-6ecc-11eb-8028-e08ec6f28d0d.png)

**Comment by ggerganov** [comment]
What are the drawbacks of having the wasm binary inside the .js file?

**Comment by thisconnect** [comment]
Size?

**Comment by ggerganov** [comment]
With `GGWAVE_WASM_SINGLE_FILE=ON` the size of the produced `libggwave.js` is `159 kB`.
With `GGWAVE_WASM_SINGLE_FILE=OFF` the sizes are:
- `libggwave.js` - `61 kB`
- `libggwave.wasm` - `72 kB`

So the difference between single-file and non-single-file is `26 kB`. I like the single-file mode because it allows you to simply use it locally. With the `.wasm` file you need to [start an HTTP server](https://emscripten.org/docs/getting_started/Tutorial.html#generating-html).

Not sure about the performance - I wouldn't be surprised if single file loads faster.

In any case, it is now possible to generate both options using the new CMake option.
