### ISSUE TITLE
Final config for TxProtocols.

### ISSUE THREAD

**Issue by solitarysp** [ggerganov/ggwave#43]
Thank you Gwave team, your library is very helpful to me.
However when I use it, I'm noticing that TxProtocols is final in `ggwave.h`
With default parameters, are these the best parameters? should i edit it or not?
![image](https://user-images.githubusercontent.com/20993683/126251164-e5d109c2-c499-4f57-a9ce-f96e2251c003.png)

**Comment by ggerganov** [comment]
Hi, these are the default set of protocols that I selected and I think generally work well enough.
Not sure if they are the best - it depends on the speed/robustness that you want to achieve in your specific application.

Technically, you don't want to modify these as they are part of the library.
Instead, ggwave allows you to create your own custom protocols.

For an example how to create custom protocols, you can check the `r2t2` example:

- Tx part: https://github.com/ggerganov/ggwave/blob/master/examples/r2t2/main.cpp#L45-L51
- Rx part: https://github.com/ggerganov/ggwave/blob/master/examples/r2t2/r2t2-rx.cpp#L314-L337

Let me know if you encounter any problems.

**Comment by solitarysp** [comment]
> Hi, these are the default set of protocols that I selected and I think generally work well enough.
> Not sure if they are the best - it depends on the speed/robustness that you want to achieve in your specific application.
> 
> Technically, you don't want to modify these as they are part of the library.
> Instead, ggwave allows you to create your own custom protocols.
> 
> For an example how to create custom protocols, you can check the `r2t2` example:
> 
> * Tx part: https://github.com/ggerganov/ggwave/blob/master/examples/r2t2/main.cpp#L45-L51
> * Rx part: https://github.com/ggerganov/ggwave/blob/master/examples/r2t2/r2t2-rx.cpp#L314-L337
> 
> Let me know if you encounter any problems.

Thanks. However, I still do not quite understand the meaning of some config, can you explain it to me?
![image](https://user-images.githubusercontent.com/20993683/126444890-b707fb0c-aba7-45c1-b788-8a9faae6f14f.png)
**freqStart, framesPerTx, bytesPerTx** I still don't understand the real influence of these parameters.

**Comment by ggerganov** [comment]
These parameters control the modulation parameters.
See detailed explanation of how the modulation works in the [README](https://github.com/ggerganov/ggwave#modulation-tx) of this repository.

The `freqStart` parameter corresponds to `F0`. For example setting `freqStart = 30` means that `F0` will be located in the `30th` frequency bin of the FFT. Since we have `1024` bins and the base sampling rate is `48000`, bin `30` will correspond to frequency of `1406.25 Hz`. Effectively, with this parameter you can shift the frequency of the transmission up and down.

The `framesPerTx` parameter controls how long each data chunk is transmitted. Increasing this parameter will make the transmission slower, but easier to receive.

The `bytesPerTx` parameter controls how much bytes are encoded within each chunk of data. Increasing this parameter would increase the data rate of the transmission, but it would require a wider range of frequencies (i.e. wider frequency band).

The easiest way to get a better understanding of the parameters is to start modifying them and see how the spectrogram of the signal changes. I have made a simple browser tool exactly for this purpose:

https://spectrogram.ggerganov.com

Open the link in your browser and start playing some `ggwave` messages to see their spectrogram.
Here is what a sample spectrogram looks like:

https://user-images.githubusercontent.com/1991296/126526794-8bae06c9-eb1d-4338-8895-e379bed7901c.mp4

**Comment by solitarysp** [comment]
Sorry, I read your reply the other day. However, due to work, I can't reply right away.
Thank you for the very useful information. There are some problems using the lib, maybe I will send some pull requests to your lib :D. Hope you will take some time to review.
