### ISSUE TITLE
ggwave.js doesn't have much options like waver.js

### ISSUE THREAD

**Issue by jitendra1607** [ggerganov/ggwave#77]
I am trying to receive a message on the web page (https://github.com/ggerganov/ggwave/blob/master/examples/arduino-rx-web/index-tmpl.html) without any success.

it works great with the waver android app using the following settings in screenshots.

![photo1662395027 (1)](https://user-images.githubusercontent.com/22209352/188490644-46168f72-b974-4b5a-91e1-1909c75c9aa4.jpeg)
![photo1662395027](https://user-images.githubusercontent.com/22209352/188490661-42b9a440-ceb0-47cf-9aba-0afaa3103861.jpeg)

But I could not find the same settings in ggwave.js. Please pay attention to the following console warning "[Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)"

**Comment by jitendra1607** [comment]
I don't think so because 'https://waver.ggerganov.com/' is capturing data with the above settings as shown in screenshots. However 'https://ggwave-js.ggerganov.com/' is unable to capture data, and I couldn't find 'MT_FASTEST' in ggwave object from ggwave.js library.

**Comment by jitendra1607** [comment]
i tried to play 'https://user-images.githubusercontent.com/1991296/168469004-aeb9b9fe-cf81-4db7-b602-62e4ae659341.mp4' in a smartphone while the webpage 'https://ggwave-js.ggerganov.com/' opened in the laptop for capturing data. The webpage not capturing properly and show garbage data sometimes.

**Comment by ggerganov** [comment]
Hi, I just pushed a change to `master` that adds the `MT` protocols to the emscripten port of `ggwave`.

Additionally, there are now functions for setting the `freqStart` parameter of the protocols through JS:

https://github.com/ggerganov/ggwave/blob/d02960259bbf44c30eaf941a35e9aaf4510013c2/bindings/javascript/emscripten.cpp#L120-L130

See an example here:

https://github.com/ggerganov/ggwave/blob/d02960259bbf44c30eaf941a35e9aaf4510013c2/examples/arduino-rx-web/index-tmpl.html#L98-L101

In the video that you posted, I was still trying out different settings so the protocol that I used is no longer supported.
Instead, you should use the `MT` protocols that are currently available in `ggwave`.

You cannot use https://ggwave-js.ggerganov.com/ to receive `Fixed-length` messages, because it is configured to listen for variable-length messages. See explanation here:

https://github.com/ggerganov/ggwave/blob/d02960259bbf44c30eaf941a35e9aaf4510013c2/include/ggwave/ggwave.h#L105-L115

---

You can use the https://arduino-rx.ggerganov.com/ example to receive `MT` messages with `Fixed-length = 16` and `DSS` enabled.

My advice is to first try using the `Waver` app with `MT` protocol to send messages to https://arduino-rx.ggerganov.com/
Make sure that the `Freq shift` in your `Waver` app is disabled. Let me know if this works.

**Comment by jitendra1607** [comment]
@ggerganov I tried this and it is working very well. Thank you.
